# Generated by Django 4.2.20 on 2025-04-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alderman',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('date_elected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondoProject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('alderman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.alderman')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('nbhd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('emperor', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('taxkey', models.CharField(blank=True, max_length=45, null=True)),
                ('style', models.CharField(blank=True, max_length=45, null=True)),
                ('extwall', models.CharField(blank=True, max_length=45, null=True)),
                ('stories', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('finished_sqft', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('full_bath', models.IntegerField(blank=True, null=True)),
                ('half_bath', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('condo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.condoproject')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.district')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.location')),
                ('nbhd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MilwaukeeProperties.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealtorCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MilwaukeeProperties.property')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.realtor')),
            ],
        ),
        migrations.AddField(
            model_name='realtor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MilwaukeeProperties.realtorcompany'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MilwaukeeProperties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MilwaukeeProperties.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=280, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MilwaukeeProperties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MilwaukeeProperties.user')),
            ],
        ),
    ]
