# Generated by Django 4.2.20 on 2025-04-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='prop_id',
        ),
    ]
