# Generated by Django 4.2.20 on 2025-04-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0002_rename_location_property_prop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
