# Generated by Django 4.2.20 on 2025-04-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip',
        ),
    ]
