# Generated by Django 4.2.20 on 2025-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0004_remove_location_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alderman',
            name='date_elected',
        ),
        migrations.AddField(
            model_name='alderman',
            name='year_elected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
