# Generated by Django 4.2.20 on 2025-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0005_remove_alderman_date_elected_alderman_year_elected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='nbhd',
            field=models.CharField(default=6969, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
