# Generated by Django 4.2.20 on 2025-04-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0006_alter_property_nbhd_delete_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
