# Generated by Django 5.2 on 2025-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilwaukeeProperties', '0010_alter_favorite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
